spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
    open-in-view: false

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.orm.jdbc.bind: trace



#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/JpashopMysql?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: 1234
#
#jpa:
#  open-in-view: true
#  hibernate:
#    ddl-auto: create
#    naming:
#      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    use-new-id-generator-mappings: false
#  show-sql: true
#  properties:
#    hibernate.format_sql: true
#    dialect: org.hibernate.dialect.MySQL8InnoDBDialect

